# Build settings
highlighter: pygments
markdown: kramdown

# Site settings
title: "Emmanuel Calvet"
description: > # this means to ignore newlines until "email:"
   Phd student in the fields of classical and quantum artificial intelligence.

#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/coverfractal.png"

name: 'Emmanuel Calvet'
author: 'Emmanuel Calvet'
author_image: "/assets/images/author.jpg"

paginate:	5

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: emmanuel.calvet@usherbrooke.ca
  facebook:
  flickr:
  github: ManuNeuro
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://manuneuro.github.io/EmmanuelCalvet.github.io/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/EmmanuelCalvet/"

#
# !! You don't need to change any of the configuration flags below !!

#permalink: /:title/

# The release of Jekyll Now that you're using
#version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # LaTeX
  math_engine: mathjax
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


# social icons and sharing options
#social:
#  - icon:	twitter
#    url:	https://twitter.com/samyonski
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/samyonski
#    desc: Connect with me on facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
